#!/usr/bin/env bash

SOURCES=${SOURCES-/sources}
TARGET=${TARGET-${SOURCES}}
WORKSPACE=${WORKSPACE-/workspace}

RPM_BUILD_SOURCES=$(rpmbuild --eval '%{_sourcedir}')
RPM_BUILD_RPMS=$(rpmbuild --eval '%{_rpmdir}')
RPM_BUILD_SRPMS=$(rpmbuild --eval '%{_srcrpmdir}')

# make a copy
cp -R ${SOURCES}/* ${WORKSPACE}/.

# fix permissions on working copy
chown root:root ${WORKSPACE}/*

# copy any non-spec files to source directory
find ${WORKSPACE} -mindepth 1 ! -name "*.spec" \
    -exec cp {} ${RPM_BUILD_SOURCES}/. \;

# install deps and fetch any external sources
# then do an RPM BUILD
find ${WORKSPACE} -maxdepth 1 -type f -name "*.spec" \
    -exec yum-builddep -y {} \; \
    -exec spectool --sourcedir --get-files {} \; \
    -exec rpmbuild ${RPMBUILD_OPTS} -ba --clean {} \;

# extract RPMs
find ${RPM_BUILD_RPMS} -name "${COMPONENT}*.rpm" \
    -exec mv {} ${TARGET} \;

# extract SRPMs
find ${RPM_BUILD_SRPMS} -name "${COMPONENT}*.rpm" \
    -exec mv {} ${TARGET} \;
