#!/usr/bin/env bash

HOOKS_DIR=${ACTIVEMQ_RUN}/hooks
CONF_DIR=${ACTIVEMQ_RUN}/conf

# run all hooks
[[ -d ${HOOKS_DIR} ]] && find ${HOOKS_DIR} \
    -type f -name "*.sh" \
    -exec echo "Executing {}" \; \
    -exec {} \;

# load any runtime configurations
[[ -d ${CONF_DIR} ]] && find ${CONF_DIR} \
    -type f \
    -exec bash -c \
        'for file do
            DEST=${file/"${ACTIVEMQ_RUN}"/"${ACTIVEMQ_HOME}"};
            [[ -e ${DEST} ]] && ln -sf $file ${DEST} && echo "Replaced ${DEST}";
        done' -- {} \;

# start activemq in the foreground
ACTIVEMQ_OPTS=${ACTIVEMQ_OPTS} ${ACTIVEMQ_HOME}/bin/activemq console $@
